import requests
import logging, os
from dotenv import load_dotenv
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

load_dotenv()

api_key = os.getenv("ai_api_key")

def read_system_instructions(file_path):
    '''Read system instructions from a file
    Args:  
        file_path (str): The path to the file containing system instructions
    Returns:
        str: The system instructions read from the file, or None if an error occurs
    '''
    try:
        path = Path.cwd() / file_path
        with open(rf"{path}", 'r', encoding='utf-8') as f:
            return f.read().strip()
    except Exception as e:
        logging.error(f"Error reading system instructions from {file_path}: {e}")
        return None

def generate_response(prompt):
    '''Generate a response from the Gemini API based on a user prompt
    Args:        
        prompt (str): The user prompt to send to the Gemini API
    Returns:
        str: The response generated by the Gemini API, or None if an error occurs
    '''
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    headers = {
        "x-goog-api-key": api_key,
        "Content-Type": "application/json"
    }
    system_prompt = read_system_instructions("app/system_instructions/system_prompt.txt")
    full_prompt = f"{system_prompt}\n\nUser: {prompt}"

    data = {
        "contents": [
            {"parts": [{"text": full_prompt}]}
        ]
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        result = response.json()

        candidates = result.get("candidates", [])
        if not candidates:
            logging.warning("No candidates returned from API.")
            return None

        parts = candidates[0].get("content", {}).get("parts", [])
        response_text = " ".join(part.get("text", "") for part in parts)
        return response_text.strip() if response_text else None

    except requests.exceptions.RequestException as e:
        logging.error(f"API request failed: {e}")
        return None

if __name__ == "__main__":
    prompt = "What is the capital of France"
    response = generate_response(prompt)
    print(f"Prompt: {prompt}\nResponse: {response}")
