import requests
import logging, os, json, re
from dotenv import load_dotenv
from pathlib import Path
from logic.session import save_chat, get_chat_history
from utils.retry import retry

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

load_dotenv()

api_key = os.getenv("ai_api_key")

def read_system_instructions(file_path):
    '''Read system instructions from a file
    Args:  
        file_path (str): The path to the file containing system instructions
    Returns:
        str: The system instructions read from the file, or None if an error occurs
    '''
    try:
        path = Path.cwd() / file_path
        with open(rf"{path}", 'r', encoding='utf-8') as f:
            return f.read().strip()
    except Exception as e:
        logging.error(f"Error reading system instructions from {file_path}: {e}")
        return None

@retry(max_attempts=3, delay=2.0, backoff=2.0, exceptions=(requests.exceptions.RequestException,))
def generate_response(session_id, prompt):
    '''Generate a response from the Gemini API based on a user prompt
    Args:
        session_id (str): Unique session state identifier
        prompt (str): The user prompt to send to the Gemini API
    Returns:
        str: The response generated by the Gemini API, or None if an error occurs
    '''
    url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
    headers = {
        "x-goog-api-key": api_key,
        "Content-Type": "application/json"
    }
    system_prompt = read_system_instructions("agent/system_instructions/system_prompt.txt")
    history = get_chat_history(session_id)
    if history:
        full_prompt = f"{system_prompt}\n\nConversation History: {history}\n\nUser: {prompt}"
    else:
        full_prompt = f"{system_prompt}\n\nUser: {prompt}"

    data = {
        "contents": [
            {"parts": [{"text": full_prompt}]}
        ]
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        result = response.json()

        candidates = result.get("candidates", [])
        if not candidates:
            logging.warning("No candidates returned from API.")
            return None

        parts = candidates[0].get("content", {}).get("parts", [])
        response_text = " ".join(part.get("text", "") for part in parts)
        ai_response = response_text.strip() if response_text else None
        if ai_response:
            match = re.search(r'```json\s*(\{.*?\})\s*```', ai_response, re.DOTALL)
            if match:
                json_str = match.group(1)
                parsed = json.loads(json_str)
                question = parsed.get("Question")
                complete_info = parsed.get("CompleteInfo")
                if question:
                    conversation = f"User: {prompt}\n\nAI: {question}"
                    status = save_chat(session_id, conversation)
                
                return parsed
        return None
    except requests.exceptions.RequestException as e:
        logging.error(f"API request failed: {e}")
        return None


